[project]
name = "dative_chemprop"
version = "0.1.0"
description = ""
authors = [{ name = "tmj", email = "mj_t@zju.edu.cn" }]
requires-python = ">=3.11,<3.13"
readme = "README.md"
license = "MIT"
dependencies = [
    "rdkit~=2024.3",
    "scikit-learn<1.6",
    "pandas>=2.2.3,<3",
    "seaborn>=0.13.2,<0.14",
    "chemprop>=2.1.0,<3",
    "pydantic>=2.10.6,<3",
    "patchworklib>=0.6.5,<0.7",
    "pycirclize>=1.9.0,<2",
    "matplotlib>=3.10.1,<4",
    "scikit-fingerprints>=1.12.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ipykernel>=6.30.1",
    "ipywidgets>=8.1.7",
]
